version: "3.8"

services:
 usuarios:
  container_name: usuarios
  build:
   context: ./Usuarios
   dockerfile: Dockerfile
  command: bash -c 'while !</dev/tcp/dbRadio/3306; do sleep 1; done; npm start'
  restart: on-failure
  ports:
   - 8002:8002
  networks:
   - radio
  depends_on:
   - dbRadio

 equipos:
  container_name: equipos
  build:
   context: ./Equipos
   dockerfile: Dockerfile
  command: bash -c 'while !</dev/tcp/dbRadio/3306; do sleep 1; done; npm start'
  restart: on-failure
  ports:
   - 8003:8003
  networks:
   - radio
  depends_on:
   - dbRadio

 componentes:
  container_name: componentes
  build:
   context: ./Componentes
   dockerfile: Dockerfile
  command: bash -c 'while !</dev/tcp/dbRadio/3306; do sleep 1; done; npm start'
  restart: on-failure
  ports:
   - 8004:8004
  networks:
   - radio
  depends_on:
   - dbRadio

 mantenimientos:
  container_name: mantenimientos
  build:
   context: ./Mantenimientos
   dockerfile: Dockerfile
  command: bash -c 'while !</dev/tcp/dbRadio/3306; do sleep 1; done; npm start'
  restart: on-failure
  ports:
   - 8005:8005
  networks:
   - radio
  depends_on:
   - dbRadio

 dbRadio:
  container_name: dbRadio
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: on-failure
  expose:
   - "3306"
  ports:
   - "3306:3306"
  networks:
   - radio
  environment:
   MYSQL_DATABASE: vinculacion
   MYSQL_ALLOW_EMPTY_PASSWORD: ok
   MYSQL_ROOT_PASSWORD:
   MYSQL_USER: root
   MYSQL_PASSWORD:
   MYSQL_ROOT_HOST: "%"

networks:
 radio:
  driver: bridge
